#!/usr/bin/env python3
"""Story 2 spike: proves the CAP-6 -> CAP-7 handoff shape.

A toy analysis: computes one real number (sum of squares 1..10) and writes
it, with the AD-7 provenance comment as the first line, into
manuscript/generated/spike_number.tex for main.tex to \\input{}. This is a
feasibility spike, not the real analysis pipeline -- no error-parsing or
skill tooling here (that's story 7's scope).
"""
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = "analysis/scripts/spike_number.py"
OUTPUT_PATH = REPO_ROOT / "manuscript" / "generated" / "spike_number.tex"


def compute_number() -> int:
    """Toy computation: sum of squares 1..10. Stands in for a real analysis result."""
    return sum(n * n for n in range(1, 11))


def git_short_hash() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def main() -> None:
    value = compute_number()
    short_hash = git_short_hash()
    provenance = f"% Generated by {SCRIPT_PATH} @ {short_hash} -- do not edit by hand\n"
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(provenance + f"{value}\n")
    print(f"Wrote {value} to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
